# Site settings
title: "Nahúm García"
description: "Minimalist Jekyll theme for documentation site"
baseurl: "https://nahumgarcia.github.io" # required if used under gh-pages branch, else (under master branch) just leave empty/blank
url: ""
author: "Nahúm García"

# Build settings
kramdown:
  input: GFM
permalink: pretty

# Third-party services
# just leave empty to disable it
google_analytics:
disqus_shortname: 

plugins:
  - jekyll-sitemap

exclude: ["LICENSE", "README.md", "CNAME", "vendor", "Gemfile", "script"]
