# Site settings
title: "Nahúm García"
description: "Blog personal"
baseurl: "" # required if used under gh-pages branch, else (under master branch) just leave empty/blank
url: "https://nahumgarcia.github.io"
author: "Nahúm García"

# Build settings
kramdown:
  input: GFM
permalink: pretty

#Galerías de fotos
collections:
  galleries:
    output: true
    permalink: /photos/:name/

# Third-party services
# just leave empty to disable it
google_analytics:
disqus_shortname: 

plugins:
  - jekyll-sitemap

exclude: ["LICENSE", "README.md", "CNAME", "vendor", "Gemfile", "script"]
