# Site settings
title: "Nahúm García"
description: "Blog personal"
baseurl: "" # Así debe quedar si es un sitio de usuario.
url: "https://nahumgarcia.com"
author: "Nahúm García"

# Build settings
kramdown:
  input: GFM
permalink: pretty

# Third-party services
# just leave empty to disable it
google_analytics:
disqus_shortname: 

collections:
  galleries:
    output: true
    permalink: /photos/:name/
    # Añade esto para que Jekyll reconozca la carpeta:
    output: true
    title: Galerías

plugins:
  - jekyll-sitemap

exclude: ["LICENSE", "README.md", "CNAME", "vendor", "Gemfile", "script"]
