# Site settings
title: "Nahúm García"
description: "Blog personal"
baseurl: "" # Así debe quedar si es un sitio de usuario.
url: "https://nahumgarcia.com"
author: "Nahúm García"

# Build settings
kramdown:
  input: GFM
permalink: pretty

collections_dir: content

collections:
  photos:
    output: true
    permalink: /fotos/post/:name/
  photoalbums:
    output: true
    permalink: /fotos/album/:name/
    title: Álbumes

plugins:
  - jekyll-sitemap

exclude: ["LICENSE", "README.md", "CNAME", "vendor", "Gemfile", "script"]

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "photos"
    values:
      layout: "photo_post"
